dist: bionic

language: haxe

os:
  - linux
  - osx

git:
  depth: 2

haxe:
  - "3.4.7"
  - "4.0.5"
  - development

env:
  - HAXE_TARGET=cpp
  - HAXE_TARGET=cs
  - HAXE_TARGET=eval
  - HAXE_TARGET=flash
  - HAXE_TARGET=java
  - HAXE_TARGET=js
  - HAXE_TARGET=jvm
  - HAXE_TARGET=lua
  - HAXE_TARGET=neko
  - HAXE_TARGET=node
  - HAXE_TARGET=php
  - HAXE_TARGET=php7
  - HAXE_TARGET=python

matrix:
  fast_finish: true
  allow_failures:
    - haxe: 4.0.5
      env: HAXE_TARGET=cpp     # see https://github.com/HaxeFoundation/haxe/issues/9007
    - haxe: development
    - env: HAXE_TARGET=eval
    - env: HAXE_TARGET=flash   # see https://github.com/travis-ci/travis-ci/issues/8481
    - env: HAXE_TARGET=jvm
    - env: HAXE_TARGET=lua     # too many local variables, see https://github.com/HaxeFoundation/haxe/issues/5243
    - os: osx
  exclude:
    - haxe: 3.4.7
      env: HAXE_TARGET=eval
    - haxe: 3.4.7
      env: HAXE_TARGET=jvm
    - haxe: 3.4.7
      os: osx
    - haxe: development
      os: osx

install:
  #- haxelib git tink_io https://github.com/haxetink/tink_io pure
  #- haxelib git tink_cli https://github.com/haxetink/tink_cli pure
  #- haxelib git travix https://github.com/back2dos/travix && pushd . && cd $(haxelib config)travix/git && haxe build-neko.hxml && popd
  #- haxelib run travix install
  - haxelib dev haxe-strings .
  - haxelib install haxe-doctest
  - haxelib install travix

script:
  - haxelib run travix $HAXE_TARGET
